stages:
  - build

update-images:
  image: docker:24.0
  stage: build
  services:
    - name: docker:24.0-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - .gitlab/CI/update-images.sh


