stages:
  - check
  - build

check-for-changes:
  image: alpine:3.18
  stage: check
  before_script:
    - apk add --no-cache git grep
  script:
    - .gitlab/CI/check-for-changes.sh
  artifacts:
    paths:
      - "./images/changed_images"
    expire_in: 2 days


update-images:
  image: docker:24.0
  stage: build
  needs:
    - job: check-for-changes
      artifacts: true
  services:
    - name: docker:24.0-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - .gitlab/CI/update-images.sh
