stages:
  - check
  - prepare-jobs
  - build

check-for-changes:
  image: alpine:3.18
  stage: check
  before_script:
    - apk add --no-cache git grep
  script:
    - .gitlab/CI/check-for-changes.sh
  artifacts:
    paths:
      - "./changed_images"
    expire_in: 2 days

create-jobs:
  image: debian:stable-slim
  stage: prepare-jobs
  needs:
    - job: check-for-changes
      artifacts: true
  script:
    - .gitlab/CI/create-jobs.sh
  artifacts:
    paths:
      - ".gitlab/CI/dynamic-gitlab-ci.yml"
    expire_in: 2 days

trigger-builds:
  stage: build
  trigger:
    include:
      - artifact: .gitlab/CI/dynamic-gitlab-ci.yml # this file is generated on runtime in the prepare-jobs stage
        job: create-jobs
    strategy: depend
    forward:
      pipeline_variables: true
