FROM registry.fedoraproject.org/fedora-toolbox:38

RUN dnf install -y zsh

RUN dnf install -y latexmk
RUN dnf install -y texlive
RUN dnf install -y texlive-collection-langgerman
RUN dnf install -y texlive-collection-latexextra
RUN dnf install -y texlive-latexindent