default:
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# unfortunately, pipeline configs require at least one job to succeed.
# So here is a dummy job that always runs, even if no images changed
dummy:
  stage: build
  script:
    - echo "updated all images"
